# https://code.visualstudio.com/api/working-with-extensions/continuous-integration
name: textmate-yara

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - github-actions

jobs:
  build:
    strategy:
      matrix:
        # test against the following major versions of Node
        node: [ '8' ]
        os: [ ubuntu-latest ]
        # os: [ ubuntu-latest, windows-latest, macOS-latest ]
        # node: [ '8', '10', '12' ]
    name: Testing on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
      with:
        # only use the latest files
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      # might work for linux. update display variable so vscode will open
      # npm commands are defined in package.json the "scripts" section
    - run: |
        export DISPLAY=':99.0' /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        npm install
        npm run build
        npm test
    - shell: bash
